version: '3'

services:
  postgres:
    image: postgres:latest
    ports:
      - "5532:5432"
    environment:
      POSTGRES_USER: fajriillahi
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: localdb
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:

