_format_version: "2.1"

services:

- name: hello-service
  url: http://hello-service:80
  routes:
  - name: hello-route
    paths:
    - /hello
    
plugins:
- name: cors
  config:
    origins:
      - https://google.com
      - https://www.google.com
    methods:
    - GET
    - POST 
    headers:
    - Accept
    - Accept-Version
    - Content-Length
    - Content-MD%
    - Content-Type
    - Date 
    - X-Auth-Token
    exposed_headers:
    - X-Auth-Token 
    credentials: true
    max_age: 3600
    preflight_continue: false

- name: rate-limiting
  config:
    # second: 5
    hour: 10
    policy: local
    fault_tolerant: true
    hide_client_headers: false
    redis_ssl: false
    redis_ssl_verify: false
# comment these if you don't want to store rate limiting data in redis
    # policy: redis
    # redis_host: 172.27.59.36
    # redis_password: example

- name: ip-restriction 
  config:
    allow:
    - 54.13.21.1
    - 143.1.0.0/24
    - 172.25.0.1
    # deny:
    # - 172.25.0.1
    status: 401
    message: Cannot grant access
    