version: "3.3"

services:
  hello-service:
    image: nginx:alpine
    volumes:
      - ./html:/usr/share/nginx/html
    ports:
      - "6969:80"
    networks:
      - shared-network

networks:
  shared-network:
    external:
      name: kong_default
