# Use the official PostgreSQL image from Docker Hub
FROM postgres:13

# Set environment variables to create a user and database
ENV POSTGRES_USER myuser
ENV POSTGRES_PASSWORD mypassword
ENV POSTGRES_DB mydb


# # Build the image
# docker build -t custom-postgres .

# # Run the container
# docker run --name pg-container -p 5432:5432 -d custom-postgres
